# Generated by Django 3.2.6 on 2025-03-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
